import './globals.css'
import Footer from './footer';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        {children}
      <footer>
        <Footer />
      </footer>
      </body>
    </html>
  )
}
